services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: rsync -a public/ /data/public/ && npm start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~18.16.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        value: 0ro0YQSMZPUeLlFRZRrhUA==
      - key: APP_KEYS
        value: hhnr5egJQIjrvRcexptGeQ==,pc7zhaDAKAc4l0ob+L7SGA==,K7NlDEwN1mgUJVmybJj1UA==,qKsA+mavUU7/PM/xQmCdOQ==
      - key: SENDGRID_API_KEY
        value: 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
      - key: CLOUDINARY_NAME
        value: dwtx9bs6k
      - key: CLOUDINARY_KEY
        value: 439263995974692
      - key: CLOUDINARY_SECRET
        value: JCIuUXrROI8GLxqr4ROXsvoAkps

